# Generated by Django 4.0.4 on 2022-04-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pays', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('periode_plus_visite', models.DateField(blank=True, null=True)),
                ('periode_moins_visite', models.DateField(blank=True, null=True)),
                ('visite_par_an', models.IntegerField()),
                ('commentaires_faits', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
